services:
  localstack:
    image: localstack/localstack:latest
    read_only: false
    ports:
      - 4566:4566
      - 4571:4571
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - GATEWAY_LISTEN=0.0.0.0:4566
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:5173
      - EXTRA_CORS_ALLOWED_HEADERS=x-api-key
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # required for some AWS services like AWS Lambda
    security_opt:
      - no-new-privileges:true
  jobsvc:
    container_name: jobsvc
    build:
      context: .
      dockerfile: services/jobsvc/Dockerfile
      target: ${ENV}
      args:
        APP_HOME: ${APP_HOME}
    env_file: ".env"
    ports:
      - ${JOB_SERVICE_PORT}:${JOB_SERVICE_PORT}
    links:
      - localstack
      - cassandra
    volumes:
      - .:${APP_HOME}
  schedulingsvc:
    container_name: schedulingsvc
    build:
      context: .
      dockerfile: services/schedulingsvc/Dockerfile
      target: ${ENV}
      args:
        APP_HOME: ${APP_HOME}
    env_file: ".env"
    ports:
      - ${SCHEDULING_SERVICE_PORT}:${SCHEDULING_SERVICE_PORT}
    links:
      - cassandra
      - rabbitmq
    volumes:
      - .:${APP_HOME}
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - ${RABBIT_PORT}:${RABBIT_PORT}
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${DB_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
  database:
    container_name: database
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - djm_pgdata:/var/lib/postgresql/data
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_USER=${DB_USERNAME}
      - CASSANDRA_PASSWORD=${CASS_PASSWORD}
    volumes:
      - djm_cassdata:/var/lib/cassandra

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  djm_pgdata:
  djm_cassdata:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local

