services:
  localstack:
    image: localstack/localstack:latest
    read_only: false
    ports:
      - 4566:4566
      - 4571:4571
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - GATEWAY_LISTEN=0.0.0.0:4566
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:5173
      - EXTRA_CORS_ALLOWED_HEADERS=x-api-key
    volumes:
      # - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"  # required for some AWS services like AWS Lambda
    security_opt:
      - no-new-privileges:true
  backend:
    build:
      context: ./backend
      target: ${ENV}
      args:
        APP_HOME: ${APP_HOME}
    env_file: ".env"
    ports:
      - 8080:8080
    links:
      - localstack
    volumes:
      - ./backend/:${APP_HOME}
  frontend:
    build:
      context: ./frontend
      target: ${ENV}
      args:
        APP_HOME: ${APP_HOME}
    env_file: ".env"
    ports:
      - 3000:3000
      - 5173:5173
    links:
      - backend
    volumes:
      - ./frontend/:${APP_HOME}

