services:
  localstack:
    image: localstack/localstack:latest
    read_only: false
    ports:
      - 4566:4566
      - 4571:4571
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      # - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"  # required for some AWS services like AWS Lambda
    security_opt:
      - no-new-privileges:true
  dts:
    build:
      context: .
      target: ${ENV}
      args:
        APP_HOME: ${APP_HOME}
    ports:
      - 8080:8080
    links:
      - localstack
    volumes:
      - ./:${APP_HOME}

